"""个人贷款产品库。

面向有贷款需求的个人(工薪、个体、自由职业等)。利率为年化,
金额单位为万元。所有利率为 2024–2025 年市场公开的主流参考区间
(结合 LPR 3.1% / 央行普惠导向 / 持牌机构合规上限 24%),
以各机构实际审批为准。真实场景可替换为对接银行 API 或本地城市产品库。
"""

# provider_type: 国有大行 / 股份制银行 / 城商行 / 政策性/贴息 / 持牌消费金融 / 保险/其他

PERSONAL_PRODUCTS = [
    {
        "id": "bank-salary-credit",
        "name": "银行工薪信用贷",
        "provider_type": "股份制银行",
        "desc_ref": "对标 招行闪电贷 / 建行快贷 / 工行融e借 / 中行中银e贷",
        "requires_collateral": False,
        "need_salary_card": True,          # 需打卡工资
        "need_social_security": True,
        "min_income": 4000,                # 元/月
        "min_work_years": 0.5,
        "min_credit": "good",
        "income_multiple": 12,             # 授信 ≈ 月收入 × 倍数
        "max_amount": 50,                  # 万元(优质客户部分可到100)
        "annual_rate_min": 3.4,
        "annual_rate_max": 10.8,
        "max_term_months": 60,
        "release_days": "当天-3 个工作日",
        "highlights": "银行低息纯信用,随借随还按日计息,提前还款一般无违约金",
        "hidden_criteria": "隐性偏好:代发工资/公积金在本行、单位为国企或规上企业、征信近半年查询≤4 次者利率与额度更优",
        "local_approval_rate": 85,
        "fit_purposes": ["consumption", "decoration", "education", "medical", "marriage", "travel", "turnover", "debt_optimize"],
    },
    {
        "id": "fund-credit",
        "name": "公积金信用贷",
        "provider_type": "股份制银行",
        "desc_ref": "对标 各行公积金专属信用贷 / 平安新一贷公积金版",
        "requires_collateral": False,
        "need_housing_fund": True,
        "min_income": 3000,
        "min_work_years": 0.5,
        "min_credit": "good",
        "fund_multiple": 120,              # 授信 ≈ 月缴存额 × 倍数(万元换算另处理)
        "income_multiple": 15,
        "max_amount": 50,
        "annual_rate_min": 3.6,
        "annual_rate_max": 9.6,
        "max_term_months": 60,
        "release_days": "1-5 个工作日",
        "highlights": "以连续公积金缴存换额度,缴存基数越高额度越大,利率优于普通消费贷",
        "hidden_criteria": "需公积金连续缴存满 6-12 个月、当前正常缴存;断缴或代缴会被拒",
        "local_approval_rate": 83,
        "fit_purposes": ["consumption", "decoration", "education", "medical", "marriage", "travel", "turnover", "debt_optimize"],
    },
    {
        "id": "gov-employee-loan",
        "name": "公职人员专属信用贷",
        "provider_type": "国有大行",
        "desc_ref": "对标 各行 公务员/事业编/教师/医生 专属贷",
        "requires_collateral": False,
        "need_occupation": ["civil_servant", "professional"],
        "min_income": 4000,
        "min_work_years": 1.0,
        "min_credit": "good",
        "income_multiple": 24,
        "max_amount": 80,
        "annual_rate_min": 3.1,
        "annual_rate_max": 7.2,
        "max_term_months": 84,
        "release_days": "1-5 个工作日",
        "highlights": "职业稳定人群专属,利率最低、额度高、期限长,是优质客群的首选",
        "hidden_criteria": "需在编在职、单位出具在职证明或代发工资在本行;编外/合同工通常不适用",
        "local_approval_rate": 92,
        "fit_purposes": ["consumption", "decoration", "education", "medical", "marriage", "travel", "turnover", "debt_optimize", "car"],
    },
    {
        "id": "house-mortgage-personal",
        "name": "个人房产抵押消费/经营贷",
        "provider_type": "国有大行",
        "desc_ref": "对标 各行 个人房抵贷 / 抵押经营贷",
        "requires_collateral": True,
        "need_house": True,
        "min_income": 3000,
        "min_work_years": 0.0,
        "min_credit": "fair",
        "collateral_ratio": 0.7,           # 房产估值 × 七成
        "max_amount": 1000,
        "annual_rate_min": 3.1,
        "annual_rate_max": 6.5,
        "max_term_months": 240,
        "release_days": "10-20 个工作日",
        "highlights": "有房即可办大额低息,额度高、期限最长可达 20-30 年,适合大额与长期需求",
        "hidden_criteria": "评估按市价约七折,房龄≤25-30 年、产权清晰;需办抵押登记,放款较慢;经营用途需营业执照",
        "local_approval_rate": 80,
        "fit_purposes": ["decoration", "turnover", "startup", "education", "medical", "debt_optimize", "consumption"],
    },
    {
        "id": "car-mortgage-personal",
        "name": "汽车抵押贷",
        "provider_type": "城商行",
        "desc_ref": "对标 各持牌机构 车抵贷(押车/不押车)",
        "requires_collateral": True,
        "need_car": True,
        "min_income": 2000,
        "min_work_years": 0.0,
        "min_credit": "fair",
        "collateral_ratio": 0.8,           # 车辆估值 × 八成
        "max_amount": 50,
        "annual_rate_min": 8.0,
        "annual_rate_max": 18.0,
        "max_term_months": 36,
        "release_days": "当天-3 个工作日",
        "highlights": "有车即可快速放款,不押车可继续开,适合有车、急用中小额人群",
        "hidden_criteria": "看车辆评估价与车龄(一般≤8 年);综合费率偏高,注意 GPS/服务费,建议短期使用",
        "local_approval_rate": 84,
        "fit_purposes": ["turnover", "consumption", "medical", "startup"],
    },
    {
        "id": "insurance-policy-loan",
        "name": "保单质押贷",
        "provider_type": "保险/其他",
        "desc_ref": "对标 寿险保单现金价值质押借款",
        "requires_collateral": True,
        "need_insurance": True,
        "min_income": 0,
        "min_work_years": 0.0,
        "min_credit": "poor",
        "collateral_ratio": 0.8,           # 保单现金价值(粗略用估值×比例)
        "max_amount": 20,
        "annual_rate_min": 5.0,
        "annual_rate_max": 6.5,
        "max_term_months": 12,
        "release_days": "当天-2 个工作日",
        "highlights": "凭寿险/年金保单现金价值借款,不查征信、放款快、几乎必过,不影响保单效力",
        "hidden_criteria": "可借额度约为保单现金价值的 80%,期限通常半年至一年需还本或续借",
        "local_approval_rate": 97,
        "fit_purposes": ["turnover", "consumption", "medical", "marriage"],
    },
    {
        "id": "gov-startup-guarantee-personal",
        "name": "创业担保贷(个人贴息)",
        "provider_type": "政策性/贴息",
        "desc_ref": "对标 人社部门 创业担保贷款(政府贴息)",
        "requires_collateral": False,
        "need_entrepreneur": True,
        "min_income": 0,
        "min_work_years": 0.0,
        "min_credit": "fair",
        "max_amount": 30,                  # 个人最高 30 万(各地略有差异)
        "annual_rate_min": 3.0,
        "annual_rate_max": 3.5,
        "max_term_months": 36,
        "release_days": "政策审核 15-30 天",
        "highlights": "政府贴息、财政担保,几乎零利率成本,是创业/个体经营者最划算的选择",
        "hidden_criteria": "需属于扶持人群并办理营业执照:高校毕业生/返乡农民工/登记失业人员个人最高 30 万元、退役军人最高 50 万元;贷款利率不超过 LPR+50BP,个人由财政全额贴息,名额与额度以当地人社政策为准",
        "local_approval_rate": 78,
        "subsidy_linked": True,
        "fit_purposes": ["startup", "turnover"],
    },
    {
        "id": "decoration-installment",
        "name": "家装专项分期",
        "provider_type": "股份制银行",
        "desc_ref": "对标 各行家装分期 / 装修贷",
        "requires_collateral": False,
        "need_salary_card": False,
        "min_income": 3000,
        "min_work_years": 0.5,
        "min_credit": "good",
        "income_multiple": 10,
        "max_amount": 30,
        "annual_rate_min": 4.0,
        "annual_rate_max": 9.0,
        "max_term_months": 60,
        "release_days": "3-7 个工作日",
        "highlights": "专为装修设计,部分银行有贴息活动,按装修合同放款、随用随还",
        "hidden_criteria": "通常需提供装修合同,资金受托支付给装修公司;手续费折算年化后要与普通信用贷比价",
        "local_approval_rate": 82,
        "fit_purposes": ["decoration"],
    },
    {
        "id": "internet-consumer-loan",
        "name": "互联网消费信用贷",
        "provider_type": "持牌消费金融",
        "desc_ref": "对标 微粒贷 / 借呗 / 京东金条 / 度小满",
        "requires_collateral": False,
        "min_income": 2000,
        "min_work_years": 0.0,
        "min_credit": "fair",
        "income_multiple": 6,
        "max_amount": 20,
        "annual_rate_min": 10.95,
        "annual_rate_max": 24.0,
        "max_term_months": 24,
        "release_days": "实时-当天",
        "highlights": "线上秒批秒到,门槛低、无需线下,适合征信一般或急用的小额短期需求",
        "hidden_criteria": "利率因人而异,综合年化(APR)以 24% 为监管事实参考线;多头借贷会被风控,仅建议短期周转、避免以贷养贷",
        "local_approval_rate": 88,
        "fit_purposes": ["consumption", "turnover", "medical", "travel", "marriage", "education"],
    },
    {
        "id": "licensed-emergency-loan",
        "name": "持牌机构应急小额贷",
        "provider_type": "持牌消费金融",
        "desc_ref": "对标 各持牌消金公司 应急周转产品",
        "requires_collateral": False,
        "min_income": 1500,
        "min_work_years": 0.0,
        "min_credit": "poor",
        "income_multiple": 4,
        "max_amount": 5,
        "annual_rate_min": 18.0,
        "annual_rate_max": 24.0,
        "max_term_months": 12,
        "release_days": "实时-当天",
        "highlights": "门槛最低、放款最快,征信欠佳也可尝试,但成本高,仅作最后的短期应急",
        "hidden_criteria": "务必认准持牌机构,综合年化(APR)以 24% 为监管事实参考线;警惕砍头息/套路贷,借前算清总还款总额",
        "local_approval_rate": 90,
        "fit_purposes": ["turnover", "medical", "consumption"],
    },
]

# 收入形式对授信的影响系数(打卡工资最优,现金/混合打折)
INCOME_TYPE_FACTOR = {"salary": 1.0, "business": 0.9, "cash": 0.75}
